import type { AppLocale } from "@/lib/locale/app-locale";

export const ADMIN_USER_DETAILS_COPY = {
  en: {
    users: "Users",
    userDetails: "User Details",
    title: "User Details",
    subtitle: "Review account, portfolio, preferences, and login history.",
    backToUsers: "Back to Users",
    editUser: "Edit User",
    profile: "Profile",
    portfolio: "Portfolio",
    sessions: "Sessions",
    role: "Role",
    status: "Status",
    email: "Email",
    joined: "Joined",
    lastSeen: "Last Seen",
    userId: "User ID",
    verified: "Verified",
    unverified: "Unverified",
    active: "Active",
    inactive: "Inactive",
    deleted: "Deleted",
    accountProfile: "Account profile",
    accountProfileDescription: "Stored contact and personal information.",
    authentication: "Authentication",
    authenticationDescription: "Linked sign-in methods and account access.",
    mobile: "Mobile",
    gender: "Gender",
    address: "Address",
    preferredLanguage: "Preferred language",
    createdAt: "Created",
    updatedAt: "Updated",
    lastSeenIp: "Last seen IP",
    lastSeenDevice: "Last seen device",
    deviceType: "Device type",
    browser: "Browser",
    operatingSystem: "Operating system",
    rawUserAgent: "Raw user-agent",
    passwordLogin: "Password login",
    linkedProviders: "Linked providers",
    available: "Available",
    unavailable: "Unavailable",
    linked: "Linked",
    noLinkedProviders: "No linked provider records",
    portfolioSummary: "Portfolio Summary",
    invested: "Known invested",
    currentValue: "Known current value",
    unrealized: "Unrealized P/L",
    holdings: "Holdings",
    watchlist: "Watchlist",
    portfolioEmail: "Portfolio email",
    enabled: "Enabled",
    disabled: "Disabled",
    holdingsTitle: (count: number) => `Holdings (${count})`,
    symbol: "Symbol",
    quantity: "Quantity",
    averageBuy: "Avg buy",
    currentPrice: "Current price",
    profitLoss: "P/L",
    action: "Action",
    preferences: "Watchlist & preferences",
    notesPresent: "Notes present",
    portfolioUpdated: "Portfolio updated",
    marketData: "Market data",
    quickInsights: "Quick insights",
    noPortfolio: "No portfolio yet",
    noPortfolioDescription: "This user has no watchlist entries or holdings.",
    watchlistOnly: "Watchlist only",
    watchlistOnlyDescription: "The user tracks stocks but has not recorded any holdings.",
    incompleteHolding: (count: number) => `${count} holding${count === 1 ? "" : "s"} need quantity or buy price.`,
    requiresReview: (count: number) => `${count} holding${count === 1 ? "" : "s"} currently require review.`,
    portfolioCurrent: "Portfolio calculations use the latest available market data.",
    emailDigestEnabled: "Daily portfolio email is enabled.",
    emailDigestDisabled: "Daily portfolio email is disabled.",
    recentSessions: "Login sessions",
    sessionDescription: "Recorded authentication attempts, newest first.",
    total: "Total",
    successful: "Successful",
    failed: "Failed",
    revoked: "Revoked",
    loggedOut: "Logged out",
    loginTime: "Login time",
    device: "Device",
    ipAddress: "IP address",
    sessionState: "Session state",
    successfulLogin: "Successful login",
    failedLogin: "Failed login",
    recordedLogin: "Recorded login",
    noSessions: "No sessions yet",
    noSessionsDescription: "Session history will appear after the user signs in.",
    previous: "Previous",
    next: "Next",
    editAccount: "Edit account",
    accountActive: "Account active",
    saveChanges: "Save changes",
    close: "Close",
    loadError: "Could not load this user.",
    portfolioError: "Could not load portfolio details.",
    sessionsError: "Could not load session history.",
    unknown: "Unknown",
    yes: "Yes",
    no: "No",
  },
  bn: {
    users: "ব্যবহারকারী",
    userDetails: "ব্যবহারকারীর বিস্তারিত",
    title: "ব্যবহারকারীর বিস্তারিত",
    subtitle: "অ্যাকাউন্ট, পোর্টফোলিও, পছন্দ ও লগইন ইতিহাস দেখুন।",
    backToUsers: "ব্যবহারকারী তালিকায় ফিরুন",
    editUser: "ব্যবহারকারী সম্পাদনা",
    profile: "প্রোফাইল",
    portfolio: "পোর্টফোলিও",
    sessions: "সেশন",
    role: "ভূমিকা",
    status: "অবস্থা",
    email: "ইমেইল",
    joined: "যোগদান",
    lastSeen: "সর্বশেষ দেখা",
    userId: "ব্যবহারকারী আইডি",
    verified: "যাচাইকৃত",
    unverified: "যাচাই হয়নি",
    active: "সক্রিয়",
    inactive: "নিষ্ক্রিয়",
    deleted: "মুছে ফেলা",
    accountProfile: "অ্যাকাউন্ট প্রোফাইল",
    accountProfileDescription: "সংরক্ষিত যোগাযোগ ও ব্যক্তিগত তথ্য।",
    authentication: "প্রমাণীকরণ",
    authenticationDescription: "সংযুক্ত সাইন-ইন পদ্ধতি ও অ্যাকাউন্ট প্রবেশাধিকার।",
    mobile: "মোবাইল",
    gender: "লিঙ্গ",
    address: "ঠিকানা",
    preferredLanguage: "পছন্দের ভাষা",
    createdAt: "তৈরি",
    updatedAt: "হালনাগাদ",
    lastSeenIp: "সর্বশেষ আইপি",
    lastSeenDevice: "সর্বশেষ ডিভাইস",
    deviceType: "ডিভাইসের ধরন",
    browser: "ব্রাউজার",
    operatingSystem: "অপারেটিং সিস্টেম",
    rawUserAgent: "মূল user-agent",
    passwordLogin: "পাসওয়ার্ড লগইন",
    linkedProviders: "সংযুক্ত প্রদানকারী",
    available: "উপলভ্য",
    unavailable: "অনুপলভ্য",
    linked: "সংযুক্ত",
    noLinkedProviders: "কোনো সংযুক্ত প্রদানকারীর তথ্য নেই",
    portfolioSummary: "পোর্টফোলিও সারাংশ",
    invested: "জানা বিনিয়োগ",
    currentValue: "জানা বর্তমান মূল্য",
    unrealized: "অবাস্তবায়িত লাভ/ক্ষতি",
    holdings: "হোল্ডিংস",
    watchlist: "ওয়াচলিস্ট",
    portfolioEmail: "পোর্টফোলিও ইমেইল",
    enabled: "চালু",
    disabled: "বন্ধ",
    holdingsTitle: (count: number) => `হোল্ডিংস (${count})`,
    symbol: "প্রতীক",
    quantity: "পরিমাণ",
    averageBuy: "গড় ক্রয়",
    currentPrice: "বর্তমান দাম",
    profitLoss: "লাভ/ক্ষতি",
    action: "সিদ্ধান্ত",
    preferences: "ওয়াচলিস্ট ও পছন্দ",
    notesPresent: "নোট আছে",
    portfolioUpdated: "পোর্টফোলিও হালনাগাদ",
    marketData: "বাজার তথ্য",
    quickInsights: "দ্রুত তথ্য",
    noPortfolio: "এখনও পোর্টফোলিও নেই",
    noPortfolioDescription: "এই ব্যবহারকারীর কোনো ওয়াচলিস্ট বা হোল্ডিংস নেই।",
    watchlistOnly: "শুধু ওয়াচলিস্ট",
    watchlistOnlyDescription: "ব্যবহারকারী শেয়ার অনুসরণ করেন, তবে কোনো হোল্ডিংস যোগ করেননি।",
    incompleteHolding: (count: number) => `${count}টি হোল্ডিংসে পরিমাণ বা ক্রয়মূল্য প্রয়োজন।`,
    requiresReview: (count: number) => `${count}টি হোল্ডিংস এখন পর্যালোচনা করা প্রয়োজন।`,
    portfolioCurrent: "সর্বশেষ উপলভ্য বাজার তথ্য দিয়ে পোর্টফোলিও হিসাব করা হয়েছে।",
    emailDigestEnabled: "দৈনিক পোর্টফোলিও ইমেইল চালু আছে।",
    emailDigestDisabled: "দৈনিক পোর্টফোলিও ইমেইল বন্ধ আছে।",
    recentSessions: "লগইন সেশন",
    sessionDescription: "সর্বশেষটি আগে রেখে প্রমাণীকরণ প্রচেষ্টা দেখানো হয়েছে।",
    total: "মোট",
    successful: "সফল",
    failed: "ব্যর্থ",
    revoked: "বাতিল",
    loggedOut: "লগআউট",
    loginTime: "লগইন সময়",
    device: "ডিভাইস",
    ipAddress: "আইপি ঠিকানা",
    sessionState: "সেশনের অবস্থা",
    successfulLogin: "সফল লগইন",
    failedLogin: "ব্যর্থ লগইন",
    recordedLogin: "রেকর্ডকৃত লগইন",
    noSessions: "এখনও কোনো সেশন নেই",
    noSessionsDescription: "ব্যবহারকারী সাইন ইন করলে সেশন ইতিহাস দেখা যাবে।",
    previous: "আগের",
    next: "পরের",
    editAccount: "অ্যাকাউন্ট সম্পাদনা",
    accountActive: "অ্যাকাউন্ট সক্রিয়",
    saveChanges: "পরিবর্তন সংরক্ষণ",
    close: "বন্ধ করুন",
    loadError: "ব্যবহারকারীর তথ্য লোড করা যায়নি।",
    portfolioError: "পোর্টফোলিও তথ্য লোড করা যায়নি।",
    sessionsError: "সেশন ইতিহাস লোড করা যায়নি।",
    unknown: "অজানা",
    yes: "হ্যাঁ",
    no: "না",
  },
} as const;

export function getAdminUserDetailsCopy(locale: AppLocale) {
  return ADMIN_USER_DETAILS_COPY[locale];
}
