export const GUIDE_USER_ACTIVITY_GUARD_MS = 500;
export const GUIDE_AUTO_START_DELAY_MS = GUIDE_USER_ACTIVITY_GUARD_MS;
export const GUIDE_SERVER_SYNC_TIMEOUT_MS = 5000;
export const GUIDE_NUDGE_COOLDOWN_MS = 7 * 24 * 60 * 60 * 1000;
export const GUIDE_NUDGE_MAX_COUNT = 3;
export const GUIDE_LAUNCHER_PROMINENCE_MS = 7 * 24 * 60 * 60 * 1000;
