"""initial migration

Revision ID: 3418c9ad7c9f
Revises: 
Create Date: 2026-04-30 20:48:12.989025
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '3418c9ad7c9f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_market_summaries',
    sa.Column('exchange', sa.Enum('DSE', 'CSE', name='exchangecode'), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('index_name', sa.String(length=80), nullable=False),
    sa.Column('index_close', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('index_change', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('index_change_percent', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('total_volume', sa.BigInteger(), nullable=True),
    sa.Column('total_turnover', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('total_trades', sa.BigInteger(), nullable=True),
    sa.Column('advancing_issues', sa.Integer(), nullable=True),
    sa.Column('declining_issues', sa.Integer(), nullable=True),
    sa.Column('unchanged_issues', sa.Integer(), nullable=True),
    sa.Column('market_cap', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.Column('data_quality_flag', sa.Enum('OK', 'PARTIAL', 'SUSPICIOUS', name='dataqualityflag'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_market_summaries')),
    sa.UniqueConstraint('exchange', 'trade_date', 'index_name', name='uq_daily_market_summaries_exchange_date_index')
    )
    op.create_index('ix_daily_market_summaries_exchange_trade_date', 'daily_market_summaries', ['exchange', 'trade_date'], unique=False)
    op.create_table('stocks',
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('exchange', sa.Enum('DSE', 'CSE', name='exchangecode'), nullable=False),
    sa.Column('sector', sa.String(length=120), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('isin', sa.String(length=32), nullable=True),
    sa.Column('listing_date', sa.Date(), nullable=True),
    sa.Column('lot_size', sa.Integer(), nullable=True),
    sa.Column('paid_up_capital', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('market_cap', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stocks')),
    sa.UniqueConstraint('exchange', 'symbol', name='uq_stocks_exchange_symbol'),
    sa.UniqueConstraint('isin', name=op.f('uq_stocks_isin'))
    )
    op.create_index('ix_stocks_exchange_symbol', 'stocks', ['exchange', 'symbol'], unique=False)
    op.create_index('ix_stocks_sector', 'stocks', ['sector'], unique=False)
    op.create_index('ix_stocks_symbol', 'stocks', ['symbol'], unique=False)
    op.create_table('daily_prices',
    sa.Column('stock_id', sa.UUID(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('open_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('high_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('low_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('close_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('adjusted_close_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('previous_close_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('price_change', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('price_change_percent', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('day_range', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('day_range_percent', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('vwap', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('trade_count', sa.BigInteger(), nullable=True),
    sa.Column('turnover', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.Column('data_quality_flag', sa.Enum('OK', 'PARTIAL', 'SUSPICIOUS', name='dataqualityflag'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('adjusted_close_price IS NULL OR adjusted_close_price >= 0', name=op.f('ck_daily_prices_adjusted_close_price_non_negative')),
    sa.CheckConstraint('close_price >= 0', name=op.f('ck_daily_prices_close_price_non_negative')),
    sa.CheckConstraint('high_price >= 0', name=op.f('ck_daily_prices_high_price_non_negative')),
    sa.CheckConstraint('high_price >= low_price', name=op.f('ck_daily_prices_high_price_greater_than_low_price')),
    sa.CheckConstraint('low_price >= 0', name=op.f('ck_daily_prices_low_price_non_negative')),
    sa.CheckConstraint('open_price >= 0', name=op.f('ck_daily_prices_open_price_non_negative')),
    sa.CheckConstraint('volume >= 0', name=op.f('ck_daily_prices_volume_non_negative')),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], name=op.f('fk_daily_prices_stock_id_stocks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_prices')),
    sa.UniqueConstraint('stock_id', 'trade_date', name='uq_daily_prices_stock_trade_date')
    )
    op.create_index('ix_daily_prices_data_quality_flag', 'daily_prices', ['data_quality_flag'], unique=False)
    op.create_index('ix_daily_prices_source', 'daily_prices', ['source'], unique=False)
    op.create_index('ix_daily_prices_stock_trade_date', 'daily_prices', ['stock_id', 'trade_date'], unique=False)
    op.create_index('ix_daily_prices_trade_date', 'daily_prices', ['trade_date'], unique=False)
    op.create_table('technical_indicators',
    sa.Column('stock_id', sa.UUID(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('indicator_type', sa.Enum('RSI', 'SMA', 'EMA', name='indicatortype'), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('normalized_value', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('signal_score', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], name=op.f('fk_technical_indicators_stock_id_stocks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_technical_indicators')),
    sa.UniqueConstraint('stock_id', 'trade_date', 'indicator_type', 'period', name='uq_technical_indicators_stock_date_type_period')
    )
    op.create_index('ix_technical_indicators_lookup', 'technical_indicators', ['stock_id', 'indicator_type', 'period', 'trade_date'], unique=False)
    op.create_table('trading_signals',
    sa.Column('stock_id', sa.UUID(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('signal_type', sa.Enum('BUY', 'SELL', 'HOLD', name='signaltype'), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('momentum_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('trend_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('volume_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('risk_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('strategy_name', sa.String(length=120), nullable=False),
    sa.Column('components', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_trading_signals_confidence_between_zero_and_one')),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], name=op.f('fk_trading_signals_stock_id_stocks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trading_signals')),
    sa.UniqueConstraint('stock_id', 'trade_date', 'strategy_name', name='uq_signals_stock_date_strategy')
    )
    op.create_index('ix_trading_signals_stock_trade_date', 'trading_signals', ['stock_id', 'trade_date'], unique=False)
    op.create_index('ix_trading_signals_type_trade_date', 'trading_signals', ['signal_type', 'trade_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trading_signals_type_trade_date', table_name='trading_signals')
    op.drop_index('ix_trading_signals_stock_trade_date', table_name='trading_signals')
    op.drop_table('trading_signals')
    op.drop_index('ix_technical_indicators_lookup', table_name='technical_indicators')
    op.drop_table('technical_indicators')
    op.drop_index('ix_daily_prices_trade_date', table_name='daily_prices')
    op.drop_index('ix_daily_prices_stock_trade_date', table_name='daily_prices')
    op.drop_index('ix_daily_prices_source', table_name='daily_prices')
    op.drop_index('ix_daily_prices_data_quality_flag', table_name='daily_prices')
    op.drop_table('daily_prices')
    op.drop_index('ix_stocks_symbol', table_name='stocks')
    op.drop_index('ix_stocks_sector', table_name='stocks')
    op.drop_index('ix_stocks_exchange_symbol', table_name='stocks')
    op.drop_table('stocks')
    op.drop_index('ix_daily_market_summaries_exchange_trade_date', table_name='daily_market_summaries')
    op.drop_table('daily_market_summaries')
    # ### end Alembic commands ###

