import type { CommandItem } from "@/lib/command/command-types";

export const coreCommandItems: CommandItem[] = [
  {
    id: "go-dashboard",
    label: "Open Dashboard",
    description: "15-second read of market mood, breadth, signals, and events.",
    category: "NAVIGATION",
    href: "/",
    keywords: ["market", "overview", "dsex", "intelligence"],
  },
  {
    id: "go-market-pulse",
    label: "Open Market Pulse",
    description: "The stocks and market shifts that deserve your attention.",
    category: "NAVIGATION",
    href: "/market-pulse",
    keywords: ["pulse", "focus", "briefing", "attention"],
  },
  {
    id: "go-stocks",
    label: "Open Stock Explorer",
    description: "Search and filter listed DSE/CSE stocks.",
    category: "NAVIGATION",
    href: "/stocks",
    keywords: ["screener", "research"],
  },
  {
    id: "go-scanner",
    label: "Open Market Scanner",
    description: "Jump to opportunity detection categories.",
    category: "SCANNER",
    href: "/scanner",
    keywords: ["breakout", "momentum", "volume"],
  },
  {
    id: "go-signals",
    label: "Open Signal Center",
    description: "Review institutional signal explanations.",
    category: "SIGNAL",
    href: "/signals",
    keywords: ["buy", "sell", "hold"],
  },
  {
    id: "go-portfolio",
    label: "Open My Portfolio",
    description: "Review current holdings, value, risk, and what deserves attention.",
    category: "WATCHLIST",
    href: "/portfolio",
    keywords: ["holdings", "positions", "watchlist", "value"],
  },
  {
    id: "go-admin",
    label: "Open Admin Panel",
    description: "Operational dashboard, users, jobs, configuration, and email campaigns.",
    category: "ADMIN",
    href: "/admin",
    keywords: ["admin", "operations", "users", "jobs"],
  },
];
