DEFAULT_RSI_PERIOD = 14
DEFAULT_SHORT_MOVING_AVERAGE_PERIOD = 20
DEFAULT_LONG_MOVING_AVERAGE_PERIOD = 50

# Canonical live decision identity. Threshold-only changes must increment the
# threshold version even when the API shape and strategy family stay stable.
TRADING_STRATEGY_VERSION = "trading-intelligence-v2"
TRADING_THRESHOLD_VERSION = "trading-thresholds-v3"
LEGACY_TRADING_ACTION_TAXONOMY = "TRADER_RECOMMENDATION_V1"
TRADING_ACTION_TAXONOMY = "TRADER_DECISION_V2"
DECISION_TAXONOMY_VERSION = "v2"
# Version the canonical serialization used for input hashes, cache envelopes,
# immutable decision snapshots, and replay manifests. Bump this whenever the
# hashed input contract changes even if strategy thresholds do not.
TRADING_INPUT_SCHEMA_VERSION = "trading-input-v2"
TRADING_REPLAY_MANIFEST_VERSION = "trading-replay-manifest-v2"

# Operational drift gates compare consecutive like-for-like universe payloads.
# They are alerting thresholds, not trading rules and do not affect decisions.
TRADING_MONITOR_ACTION_DISTRIBUTION_DELTA = 0.25
TRADING_MONITOR_ELIGIBILITY_RATE_DELTA = 0.25

RSI_OVERSOLD_THRESHOLD = 30
RSI_OVERBOUGHT_THRESHOLD = 70

BUY_SIGNAL_CONFIDENCE_THRESHOLD = 0.65
SELL_SIGNAL_CONFIDENCE_THRESHOLD = 0.65
HOLD_SIGNAL_CONFIDENCE_THRESHOLD = 0.50

# Decision-support lookbacks and thresholds
SUPPORT_RESISTANCE_LOOKBACK = 20
DECISION_OHLCV_WINDOW = 260
DECISION_RECOMMENDATION_LOOKBACK = 90
DECISION_MIN_OHLCV_ROWS = 20
DECISION_PATTERN_RESPONSE_LIMIT = 3
SPARKLINE_CLOSE_LIMIT = 8
STALE_DATA_THRESHOLD_DAYS = 7
NEAR_LEVEL_PERCENT_THRESHOLD = 3.0
HIGH_VOLATILITY_THRESHOLD = 3.0
ELEVATED_VOLATILITY_THRESHOLD = 2.3
VOLUME_EXPANSION_RATIO = 1.8
VOLUME_THIN_RATIO = 0.45
VOLUME_CONSISTENCY_MIN_RATIO = 0.55

# Phase 2 data-eligibility policy. These are conservative starting hypotheses
# for DSE/CSE and must be calibrated by liquidity bucket in the validation phase.
ELIGIBILITY_MIN_VALID_ROWS = 50
ELIGIBILITY_ABSOLUTE_MIN_VALID_ROWS = 20
ELIGIBILITY_MIN_TRADED_SESSION_RATIO = 0.70
ELIGIBILITY_ABSOLUTE_MIN_TRADED_SESSION_RATIO = 0.50
ELIGIBILITY_MAX_MISSED_SESSIONS = 0
ELIGIBILITY_INELIGIBLE_MISSED_SESSIONS = 3
ELIGIBILITY_ROBUST_BASELINE_WINDOW = 20
ELIGIBILITY_MIN_TURNOVER_OBSERVATIONS = 10
ELIGIBILITY_MAX_PARTIAL_QUALITY_RATIO = 0.20
# A recently healthy source can recover from older generic PARTIAL flags. This
# is an interim safeguard while source-level completeness is split from
# analytical OHLCV validity.
ELIGIBILITY_RECENT_QUALITY_RECOVERY_WINDOW = 20
ELIGIBILITY_MAX_RECENT_PARTIAL_QUALITY_RATIO = 0.10
ELIGIBILITY_SESSION_LOOKBACK = 10
# No current ingestion source supplies verified adjustment-factor provenance.
ANALYTICAL_ADJUSTED_SERIES_ENABLED = False

# Technical foundation (Phase 1 overhaul)
ATR_PERIOD = 14
TREND_SLOPE_LOOKBACK = 10
RETURN_SHORT_LOOKBACK = 5
RETURN_MEDIUM_LOOKBACK = 20
# A swing high/low must be at least this many sessions old to count as a
# confirmed structural level (avoids treating the latest bar as resistance).
SUPPORT_RESISTANCE_SWING_CONFIRM_BARS = 3

# Opportunity score component weights (positive components; risk applied as penalty)
OPPORTUNITY_WEIGHT_TREND = 0.28
OPPORTUNITY_WEIGHT_MOMENTUM = 0.22
OPPORTUNITY_WEIGHT_VOLUME = 0.20
OPPORTUNITY_WEIGHT_PRICE_POSITION = 0.20
OPPORTUNITY_WEIGHT_RISK_PENALTY = 0.10

# Risk score component weights
RISK_WEIGHT_VOLATILITY = 0.25
RISK_WEIGHT_CATEGORY = 0.20
RISK_WEIGHT_LIQUIDITY = 0.20
RISK_WEIGHT_DATA_QUALITY = 0.15
RISK_WEIGHT_STALE_DATA = 0.10
RISK_WEIGHT_OVEREXTENSION = 0.10

# Overextension (operator-pump proxy) and gap-risk thresholds.
OVEREXTENSION_RETURN_20D_PERCENT = 25.0
OVEREXTENSION_ABOVE_SMA20_PERCENT = 20.0
GAP_RISK_THRESHOLD_PERCENT = 3.0
GAP_RISK_VOLATILITY_BONUS = 15.0

# Decision confidence alignment weights
CONFIDENCE_WEIGHT_TREND = 0.22
CONFIDENCE_WEIGHT_MOMENTUM = 0.18
CONFIDENCE_WEIGHT_VOLUME = 0.18
CONFIDENCE_WEIGHT_RISK = 0.18
CONFIDENCE_WEIGHT_PRICE_POSITION = 0.14
CONFIDENCE_WEIGHT_DATA = 0.10

# Confidence v2: conflicting evidence lowers confidence, and unreliable context caps it.
CONFIDENCE_CONFLICT_PENALTY = 10
CONFIDENCE_CONFLICT_BULLISH_MAX = 45  # pillar score below this conflicts with a bullish call
CONFIDENCE_CONFLICT_BEARISH_MIN = 55  # pillar score above this conflicts with a bearish call
CONFIDENCE_CAP_ILLIQUID = 40
CONFIDENCE_CAP_THIN = 60
CONFIDENCE_CAP_STALE_OR_SPARSE = 50
CONFIDENCE_HOLD_WAIT_MAX = 72

# Phase 3 canonical decision-model policy. These remain deterministic heuristic
# thresholds until the historical validation phase; they are not probabilities.
DIRECTIONAL_EVIDENCE_TREND_WEIGHT = 0.50
DIRECTIONAL_EVIDENCE_MOMENTUM_WEIGHT = 0.30
DIRECTIONAL_EVIDENCE_EVENT_WEIGHT = 0.20
DIRECTIONAL_EVIDENCE_ACTION_MIN = 55
DIRECTIONAL_EVIDENCE_CONSTRUCTIVE_MIN = 48
TRADING_RISK_WEIGHT_VOLATILITY = 0.55
TRADING_RISK_WEIGHT_CATEGORY = 0.25
TRADING_RISK_WEIGHT_OVEREXTENSION = 0.20
DATA_RELIABILITY_HIGH_MIN = 80
DATA_RELIABILITY_MEDIUM_MIN = 60
DATA_RELIABILITY_LOW_MIN = 35

# Recommendation thresholds
RECOMMENDATION_BUY_OPPORTUNITY_MIN = 55
RECOMMENDATION_HOLD_OPPORTUNITY_MIN = 48
RECOMMENDATION_BUY_HIGH_RISK_OPPORTUNITY_MIN = 65
RECOMMENDATION_BUY_RISK_MAX = 65
RECOMMENDATION_SELL_OPPORTUNITY_MAX = 38
RECOMMENDATION_SELL_RISK_MIN = 55
RECOMMENDATION_WAIT_NEAR_RESISTANCE_PERCENT = 2.5
RECOMMENDATION_BREAKOUT_VOLUME_RATIO = 1.0

# Trade plan
STOP_LOSS_VOLATILITY_BUFFER_MULTIPLIER = 0.5
MIN_RISK_REWARD_RATIO = 1.2
DEFAULT_RISK_REWARD_TARGET = 2.0
# ATR-based stop distance and the hard cap on how far a stop may sit from entry.
# DSE gap/circuit behaviour makes very tight stops unrealistic and very wide
# stops unacceptable, so risk is bounded on both ends.
TRADE_PLAN_ATR_STOP_MULTIPLIER = 2.0
TRADE_PLAN_MAX_RISK_PERCENT = 8.0
TRADE_PLAN_PULLBACK_MAX_DISTANCE_PERCENT = 8.0
TRADE_PLAN_ENTRY_ZONE_PERCENT = 1.5
TRADE_PLAN_BREAKOUT_ENTRY_BUFFER_PERCENT = 0.5
TRADE_PLAN_BREAKOUT_INVALIDATION_ATR_MULTIPLIER = 1.0
TRADE_PLAN_EXPIRY_SESSIONS = 10
TRADE_PLAN_CONTINUATION_REASSESS_SESSIONS = 5
TRADE_PLAN_TRAILING_ATR_MULTIPLIER = 2.0

# Liquidity thresholds expressed in BDT average daily turnover (not share count),
# which is the meaningful liquidity measure on DSE.
LIQUIDITY_TURNOVER_STRONG = 50_000_000.0
LIQUIDITY_TURNOVER_NORMAL = 10_000_000.0
LIQUIDITY_TURNOVER_THIN = 2_000_000.0

# Category risk mapping (DSE categories)
CATEGORY_RISK_SCORES: dict[str, int] = {
    "A": 15,
    "B": 30,
    "G": 20,
    "N": 45,
    "Z": 75,
}

# Pattern detection
PATTERN_SWING_LOOKBACK = 3
PATTERN_MIN_CANDLES = 30
PATTERN_TOLERANCE_VOLATILITY_MULTIPLIER = 0.8
# Validity filters: reversal patterns need a preceding trend and enough time
# between the two structural points to be meaningful.
PATTERN_MIN_SWING_SEPARATION = 5
PATTERN_PRIOR_TREND_MIN_PERCENT = 8.0
# Evidence-based confidence (replaces hardcoded per-pattern numbers).
PATTERN_BASE_CONFIDENCE = 45
PATTERN_EVIDENCE_TIGHT = 10
PATTERN_EVIDENCE_VOLUME = 12
PATTERN_EVIDENCE_PRIOR_TREND = 10
PATTERN_EVIDENCE_COMPLETION = 13
PATTERN_EVIDENCE_LEVEL = 8

# Swing structure signal (shared by recommendation coherence)
STRUCTURE_HIGHER = "higher_high_higher_low"
STRUCTURE_LOWER = "lower_high_lower_low"
STRUCTURE_NEUTRAL = "neutral"

# Ex-date / corporate-action guard: a one-session drop larger than this that is
# not part of a pre-existing downtrend is treated as a likely price adjustment
# (bonus/dividend/rights) rather than a genuine breakdown.
ANOMALOUS_DROP_PERCENT = 12.0
ANOMALOUS_DROP_PRIOR_WINDOW = 5

# Market regime (from index level vs its trend and market breadth)
MARKET_REGIME_BULLISH = "BULLISH"
MARKET_REGIME_NEUTRAL = "NEUTRAL"
MARKET_REGIME_BEARISH = "BEARISH"
REGIME_INDEX_LOOKBACK = 50
REGIME_INDEX_BAND_PERCENT = 0.5
REGIME_BREADTH_BULLISH_RATIO = 0.55
REGIME_BREADTH_BEARISH_RATIO = 0.40
REGIME_SUMMARY_FETCH_LIMIT = 220
REGIME_BEARISH_CONFIDENCE_CAP = 60
REGIME_EXTENDED_DISTANCE_PERCENT = 5.0
REGIME_SCORE_TREND_CAP = 30.0

# Breakout analysis
BREAKOUT_NEAR_RESISTANCE_PERCENT = 4.0

# Pulse Score (Market Pulse attention ranking)
PULSE_SCORE_VERSION = "pulse-attention-v2"
PULSE_SCORE_FOCUS_THRESHOLD = 60
PULSE_SCORE_MONITOR_THRESHOLD = 55
PULSE_SCORE_TREND_MAX = 35
PULSE_SCORE_MOMENTUM_MAX = 30
PULSE_SCORE_VOLUME_MAX = 25
PULSE_SCORE_SIGNAL_BOOST_MAX = 10
PULSE_SCORE_RISK_PENALTY_MAX = 20
PULSE_VOLUME_BREAKOUT_RATIO = 1.8
PULSE_SCORE_JUMP_THRESHOLD = 10
PULSE_FOCUS_STOCK_LIMIT = 5
PULSE_MARKET_MOVERS_LIMIT = 4
PULSE_FOCUS_SECTOR_LIMIT = 2
PULSE_FOCUS_SECTOR_EXCEPTION_LIMIT = 3
PULSE_FOCUS_SECTOR_EXCEPTION_SCORE_GAP = 10
DASHBOARD_MARKET_MOVERS_LIMIT = 5
DASHBOARD_OVERVIEW_SUMMARIES_LIMIT = 30
DASHBOARD_PRICE_WINDOW_LIMIT = 90
DASHBOARD_SIGNAL_UNIVERSE_LIMIT = 500
DASHBOARD_SIGNAL_FEED_LIMIT = 8
DASHBOARD_HEATMAP_LIMIT = 500
DASHBOARD_SECTOR_MIN_STOCKS = 3
PULSE_UNIVERSE_LIMIT = 500
PULSE_PRICE_WINDOW_LIMIT = 90

# Versioned scanner predicates. The frontend consumes the resulting condition
# matches and ranks; it does not mirror these business thresholds.
SCANNER_CONDITION_VERSION = "scanner-conditions-v1"
SCANNER_SUPPORT_REBOUND_MAX_DISTANCE_PERCENT = 4.0
SCANNER_SUPPORT_REBOUND_RSI_MAX = 45.0
SCANNER_COMPRESSION_VOLATILITY_MAX = 1.1
