DEFAULT_RSI_PERIOD = 14
DEFAULT_SHORT_MOVING_AVERAGE_PERIOD = 20
DEFAULT_LONG_MOVING_AVERAGE_PERIOD = 50

RSI_OVERSOLD_THRESHOLD = 30
RSI_OVERBOUGHT_THRESHOLD = 70

BUY_SIGNAL_CONFIDENCE_THRESHOLD = 0.65
SELL_SIGNAL_CONFIDENCE_THRESHOLD = 0.65
HOLD_SIGNAL_CONFIDENCE_THRESHOLD = 0.50

