DEFAULT_RSI_PERIOD = 14
DEFAULT_SHORT_MOVING_AVERAGE_PERIOD = 20
DEFAULT_LONG_MOVING_AVERAGE_PERIOD = 50

RSI_OVERSOLD_THRESHOLD = 30
RSI_OVERBOUGHT_THRESHOLD = 70

BUY_SIGNAL_CONFIDENCE_THRESHOLD = 0.65
SELL_SIGNAL_CONFIDENCE_THRESHOLD = 0.65
HOLD_SIGNAL_CONFIDENCE_THRESHOLD = 0.50

# Decision-support lookbacks and thresholds
SUPPORT_RESISTANCE_LOOKBACK = 20
DECISION_OHLCV_WINDOW = 260
DECISION_RECOMMENDATION_LOOKBACK = 90
DECISION_MIN_OHLCV_ROWS = 20
DECISION_PATTERN_RESPONSE_LIMIT = 3
SPARKLINE_CLOSE_LIMIT = 8
STALE_DATA_THRESHOLD_DAYS = 7
NEAR_LEVEL_PERCENT_THRESHOLD = 3.0
HIGH_VOLATILITY_THRESHOLD = 3.0
ELEVATED_VOLATILITY_THRESHOLD = 2.3
VOLUME_EXPANSION_RATIO = 1.8
VOLUME_THIN_RATIO = 0.45
VOLUME_CONSISTENCY_MIN_RATIO = 0.55

# Opportunity score component weights (positive components; risk applied as penalty)
OPPORTUNITY_WEIGHT_TREND = 0.28
OPPORTUNITY_WEIGHT_MOMENTUM = 0.22
OPPORTUNITY_WEIGHT_VOLUME = 0.20
OPPORTUNITY_WEIGHT_PRICE_POSITION = 0.20
OPPORTUNITY_WEIGHT_RISK_PENALTY = 0.10

# Risk score component weights
RISK_WEIGHT_VOLATILITY = 0.30
RISK_WEIGHT_CATEGORY = 0.20
RISK_WEIGHT_LIQUIDITY = 0.25
RISK_WEIGHT_DATA_QUALITY = 0.15
RISK_WEIGHT_STALE_DATA = 0.10

# Decision confidence alignment weights
CONFIDENCE_WEIGHT_TREND = 0.22
CONFIDENCE_WEIGHT_MOMENTUM = 0.18
CONFIDENCE_WEIGHT_VOLUME = 0.18
CONFIDENCE_WEIGHT_RISK = 0.18
CONFIDENCE_WEIGHT_PRICE_POSITION = 0.14
CONFIDENCE_WEIGHT_DATA = 0.10

# Recommendation thresholds
RECOMMENDATION_BUY_OPPORTUNITY_MIN = 55
RECOMMENDATION_HOLD_OPPORTUNITY_MIN = 48
RECOMMENDATION_BUY_HIGH_RISK_OPPORTUNITY_MIN = 65
RECOMMENDATION_BUY_RISK_MAX = 65
RECOMMENDATION_SELL_OPPORTUNITY_MAX = 38
RECOMMENDATION_SELL_RISK_MIN = 55
RECOMMENDATION_WAIT_NEAR_RESISTANCE_PERCENT = 2.5
RECOMMENDATION_BREAKOUT_VOLUME_RATIO = 1.0

# Trade plan
STOP_LOSS_VOLATILITY_BUFFER_MULTIPLIER = 0.5
MIN_RISK_REWARD_RATIO = 1.2
DEFAULT_RISK_REWARD_TARGET = 2.0

# Category risk mapping (DSE categories)
CATEGORY_RISK_SCORES: dict[str, int] = {
    "A": 15,
    "B": 30,
    "G": 20,
    "N": 45,
    "Z": 75,
}

# Pattern detection
PATTERN_SWING_LOOKBACK = 3
PATTERN_MIN_CANDLES = 30
PATTERN_TOLERANCE_VOLATILITY_MULTIPLIER = 0.8

# Breakout analysis
BREAKOUT_NEAR_RESISTANCE_PERCENT = 4.0

# Pulse Score (Market Pulse attention ranking)
PULSE_SCORE_FOCUS_THRESHOLD = 60
PULSE_SCORE_TREND_MAX = 35
PULSE_SCORE_MOMENTUM_MAX = 30
PULSE_SCORE_VOLUME_MAX = 25
PULSE_SCORE_SIGNAL_BOOST_MAX = 10
PULSE_SCORE_RISK_PENALTY_MAX = 20
PULSE_VOLUME_BREAKOUT_RATIO = 1.8
PULSE_SCORE_JUMP_THRESHOLD = 10
PULSE_FOCUS_STOCK_LIMIT = 5
PULSE_MARKET_MOVERS_LIMIT = 4
DASHBOARD_MARKET_MOVERS_LIMIT = 5
DASHBOARD_OVERVIEW_SUMMARIES_LIMIT = 30
DASHBOARD_PRICE_WINDOW_LIMIT = 90
DASHBOARD_SIGNAL_UNIVERSE_LIMIT = 500
DASHBOARD_SIGNAL_FEED_LIMIT = 8
DASHBOARD_HEATMAP_LIMIT = 500
DASHBOARD_SECTOR_MIN_STOCKS = 3
PULSE_UNIVERSE_LIMIT = 500
PULSE_PRICE_WINDOW_LIMIT = 90
