export type ScannerCategory =
  | "RSI_BREAKOUT"
  | "EMA_CROSSOVER"
  | "UNUSUAL_VOLUME"
  | "MOMENTUM_CONTINUATION"
  | "HIGH_VOLATILITY"
  | "BREAKOUT_CANDIDATES"
  | "LOW_PE"
  | "DIVIDEND_OPPORTUNITY";
